### ISSUE TITLE
In-person training location

### ISSUE THREAD

**Issue by lgatto** [lgatto/SC-ICS-Proposal#9]
@jduckles suggested

> Perhaps at a major conference of R users?

That's a good idea. The next useR meeting will be in [Stanford](http://user2016.org/) at the end of June 2016. This might be short notice, but I will get in touch with the organisers. There will be a useR in 2017, but that's a bit too far away. 

These conferences are often quite busy; the R/Bioconductor conference is also tagged onto useR this year. Instructor trainings are also quite intense, which makes me wonder if it wouldn't be counter productive. 

Let's keep this open for now. I will discuss the possibilities in the proposal.

**Comment by lgatto** [comment]
@jduckles could you comment on the requirements for the organisers of such an instructor training?

**Comment by lgatto** [comment]
I also got a positive response from the Cambridge University Bioinformatics training facility, that they could host the instructor course, if it ended up being organised in the UK.

**Comment by jduckles** [comment]
The instructor training will need two full days in a room with AV and a white board/ flip chart that can support about 20-24 people at work tables. Breakout space is useful, but not required so that instructors can go work in small groups without interrupting each other (think videoing themselves teaching on smartphones). Refreshments are optional, based on budgets and other constraints. 

Is that the kind of requirements you were looking for?

It can also be good to get a commitment form instructors being trained to go back to their home institutions and deliver a workshop within 6-12 months.

**Comment by lgatto** [comment]
Thanks, @jduckles, exactly what I was looking for.

**Comment by lgatto** [comment]
@jduckles another quick question: what is the selection process if the number of people registering is higher than 24?

**Comment by jduckles** [comment]
Basically the intent to run a workshop and the demonstrated availability and capabilities (space, resources etc) to run a workshop are usually how we prioritize. We also tend to prioritize new geographies, places we've never taught a workshop, places we don't have resident instructors etc.

Where we have taught (in the past):
http://software-carpentry.org/workshops/past/

Where our instructors are:
http://software-carpentry.org/team/

**Comment by lgatto** [comment]
Thanks!

**Comment by lgatto** [comment]
The location will be Cambridge, UK, on the 19-20 September 2016. More details and registration here http://software-carpentry.org/blog/2016/05/r-instructor-training.html.
